 // JavaScript code goes here

        // Sample products object
        const products = [
            { id:1, name: 'Product 1', rate: 1050 },
            { id:2, name: 'Product 2', rate: 15 },
            { id:3, name: 'Product 3', rate: 2000 },
            { id:4, name: 'Product 1', rate: 10 },
            { id:5, name: 'Product 2', rate: 1500 },
            { id:6, name: 'Product 3', rate: 20 },
            { id: , name: '1\' Shalimar milky garden pipe', rate: 1050 },
            { id: , name: '1/2\' Elbow brass', rate: 160 },
            { id: , name: '1/2\'×1/2\' brass valve', rate: 160 },
            { id: , name: '1/2\'×1/4\' brass valve', rate: 160 },
            { id: , name: '1/2\'×3/8 trolley pipe 40\' PTR', rate: 430 },
            { id: , name: '1/2\'×3/8\' Brass valve', rate: 160 },
            { id: , name: '11\' Tan heavy', rate: 46 },
            { id: , name: '11x40 gear gdr', rate: 790 },
            { id: , name: '12 A FULL LOCK EXTRA', rate: 35 },
            { id: , name: '12 B FULL LOCK 3/4\, rate: 35 },
            { id: , name: '12 B HALF LOCK 3/4\, rate: 35 },
            { id: , name: '12a1 10feet chain kdv', rate: 2230 },
            { id: , name: '12a1 7.5feet chain kdv', rate: 1680 },
            { id: , name: '12b1 10feet chain kdv', rate: 1830 },
            { id: , name: '12b1 7.5feet chain kdv', rate: 1310 },
            { id: , name: '12x12 pinion sainik small', rate: 2050 },
            { id: , name: '12X16 BREAK AXLE 11.5\, rate: 1050 },
            { id: , name: '13\' filter PTR', rate: 480 },
            { id: , name: '14x35 garari tempererate, rate: 280 },
            { id: , name: '16x12 pinion kartar sainik', rate: 2850 },
            { id: , name: '16X16 AXLE SUPER 14\, rate: 980 },
            { id: , name: '16X16 AXLE SUPER 15\, rate: 1050 },
            { id: , name: '16X16 AXLE SUPER 18'', rate: 1260 },
            { id: , name: '16X16 AXLE SUPER 18.5'', rate: 1295 },
            { id: , name: '16X16 AXLE SUPER 19\, rate: 1330 },
            { id: , name: '16X16 AXLE SUPER 19.5\, rate: 1370 },
            { id: , name: '16X16 AXLE SUPER 20.5\, rate: 1440 },
            { id: , name: '16X16 AXLE SUPER 29.5\, rate: 2065 },
            { id: , name: '16X16 AXLE SUPER 32\, rate: 2240 },
            { id: , name: '16X16 AXLE SUPER 34\, rate: 2380 },
            { id: , name: '16X16 AXLE SUPER 34.5\, rate: 2415 },
            { id: , name: '16X16 AXLE SUPER 36\, rate: 2520 },
            { id: , name: '16X16 AXLE SUPER 37\, rate: 2590 },
            { id: , name: '16X17 BREAK AXLE LONG', rate: 2480 },
            { id: , name: '16X17 BREAK AXLE SMALL PTL', rate: 2090 },
            { id: , name: '16X20 BREAK AXLE 11.5\, rate: 1050 },
            { id: , name: '16X20 BREAK AXLE 8.5\, rate: 1050 },
            { id: , name: '16X20 BREAK AXLE 9.5\, rate: 1090 },
            { id: , name: '17\' double filter Leylanrate, rate: 2250 },
            { id: , name: '17T m.d shaft sainik', rate: 0 },
            { id: , name: '17X22 BREAK AXLE LONG', rate: 2580 },
            { id: , name: '1kg Red gel Radiant grease', rate: 260 },
            { id: , name: '1st gear dashmesh sainik', rate: 1100 },
            { id: , name: '1ST GEAR GDR', rate: 850 },
            { id: , name: '1ST GEAR PREET 5TH', rate: 2450 },
            { id: , name: '2 hole patti big', rate: 220 },
            { id: , name: '2.5 sut katar', rate: 20 },
            { id: , name: '20X20 BREAK AXLE 8.5\, rate: 1090 },
            { id: , name: '21\' filter balti type', rate: 3850 },
            { id: , name: '2311k fld bearing', rate: 1150 },
            { id: , name: '24no. 18\' hydraulic pipe 18mm PTR', rate: 230 },
            { id: , name: '24no. 24\' hydraulic pipe 18mm PTR', rate: 280 },
            { id: , name: '24no. 30\' hydraulic pipe 18mm PTR', rate: 320 },
            { id: , name: '24no. 36\' hydraulic pipe 18mm PTR', rate: 370 },
            { id: , name: '28t came 5x6+6×6+6×7', rate: 950 },
            { id: , name: '2kg Red gel Radiant grease', rate: 520 },
            { id: , name: '2nd & 3rd gear GDR sainik', rate: 5600 },
            { id: , name: '2ND GEAR 35/31/14 DASHMESH', rate: 3130 },
            { id: , name: '2nd+3rd gear PTL sainik', rate: 5890 },
            { id: , name: '3175 housing N/T 10\, rate: 2250 },
            { id: , name: '3175 housing N/T 7\, rate: 2250 },
            { id: , name: '3175 pully all size price in inch', rate: 130 },
            { id: , name: '32208 cup degi', rate: 190 },
            { id: , name: '32x35 garari', rate: 890 },
            { id: , name: '34x30 garari', rate: 930 },
            { id: , name: '34x35 garari', rate: 930 },
            { id: , name: '36x35 garari', rate: 990 },
            { id: , name: '38 pad daimond chain', rate: 5450 },
            { id: , name: '38x35 garari tempererate, rate: 1220 },
            { id: , name: '39T hub sainik', rate: 6200 },
            { id: , name: '39x59 sainik', rate: 9100 },
            { id: , name: '3feet gun 708 pump', rate: 280 },
            { id: , name: '3kg Red gel Radiant grease', rate: 780 },
            { id: , name: '40 pad daimond chain', rate: 5650 },
            { id: , name: '43x30 garari tempererate, rate: 1350 },
            { id: , name: '43x35 garari', rate: 1150 },
            { id: , name: '5\' thippa pully 35mm', rate: 750 },
            { id: , name: '5\' thippa pully k.s', rate: 750 },
            { id: , name: '500gm pensol grease', rate: 240 },
            { id: , name: '500gm Red gel Radiant grease', rate: 140 },
            { id: , name: '50x30 garari Tempererate, rate: 1650 },
            { id: , name: '52x30 garari', rate: 1650 },
            { id: , name: '5kg Red gel Radiant grease', rate: 1300 },
            { id: , name: '5x1c adel 6205 aluminum', rate: 320 },
            { id: , name: '6 feet gun connector pipe HTP', rate: 330 },
            { id: , name: '6\' changer bush degi', rate: 980 },
            { id: , name: '6\' guidrum bush degi', rate: 690 },
            { id: , name: '6205 housing', rate: 990 },
            { id: , name: '6205 Rollon bearing', rate: 140 },
            { id: , name: '6308 housing', rate: 990 },
            { id: , name: '6309 housing D/name, rate: 690 },
            { id: , name: '6311 Gear drum housing', rate: 2580 },
            { id: , name: '6311 Gear drum housing PTL', rate: 2850 },
            { id: , name: '6mm+8mm grease housing pipe 9\'+12\'+15\, rate: 607080 },
            { id: , name: '7\' reel pully 6205', rate: 1050 },
            { id: , name: '7x35 suprod gear', rate: 280 },
            { id: , name: '8pk 1250 fenner', rate: 650 },
            { id: , name: '8x30 suprod gear tempererate, rate: 350 },
            { id: , name: '8x35 suprod gear', rate: 280 },
            { id: , name: '9\' Tan heavy', rate: 43 },
            { id: , name: '9x45 gear', rate: 560 },
            { id: , name: 'Aara big', rate: 140 },
            { id: , name: 'Air cleaner galss soft all tractor', rate: 100 },
            { id: , name: 'Alkey bolt mix', rate: 450 },
            { id: , name: 'Altinator hinno R879', rate: 4600 },
            { id: , name: 'Altinator Leyland R804', rate: 3800 },
            { id: , name: 'Altinator maruti', rate: 2580 },
            { id: , name: 'ARAM BOLT 16X139', rate: 90 },
            { id: , name: 'ARAM KARTAR PIN SIDE', rate: 1800 },
            { id: , name: 'ARAM N/T WITHOUT PIN', rate: 1800 },
            { id: , name: 'Arbidol', rate: 11400 },
            { id: , name: 'Arm hira', rate: 1750 },
            { id: , name: 'Arm kartar N/M pinwali', rate: 1750 },
            { id: , name: 'Arm kartar N/M plate', rate: 1750 },
            { id: , name: 'Arm kartar O/M pinwali', rate: 1850 },
            { id: , name: 'Arm malkit', rate: 1750 },
            { id: , name: 'Arm N/T N/M kartar', rate: 1750 },
            { id: , name: 'Arm N/T pinwali', rate: 1750 },
            { id: , name: 'Arm preet pinwali', rate: 1750 },
            { id: , name: 'Auger bush preet', rate: 290 },
            { id: , name: 'Auger bush vishal', rate: 290 },
            { id: , name: 'Auto filter set HTP pump', rate: 1500 },
            { id: , name: 'BASKET 51\' N/T', rate: 7600 },
            { id: , name: 'Basket blade Panther', rate: 550 },
            { id: , name: 'Basket saria 52\, rate: 0 },
            { id: , name: 'BCN nozzel', rate: 60 },
            { id: , name: 'BED SHAFT ROUND 30 MM', rate: 1450 },
            { id: , name: 'BED SHAFT ROUND 30 MM 63\, rate: 1450 },
            { id: , name: 'BED SHAFT ROUND 35 MM', rate: 2090 },
            { id: , name: 'BED SHAFT SQUARE', rate: 1850 },
            { id: , name: 'BED SHEET 48X84', rate: 3400 },
            { id: , name: 'BELL CRANK REAPER', rate: 1250 },
            { id: , name: 'BELL CRANK SHAFT 4 NO.', rate: 400 },
            { id: , name: 'BELL CRANK SHAFT 5 NO.', rate: 400 },
            { id: , name: 'Belt 1450', rate: 290 },
            { id: , name: 'Belt 1470 fenner', rate: 350 },
            { id: , name: 'Betterfly Nipple 8.5mm MS', rate: 120 },
            { id: , name: 'Big braketi', rate: 90 },
            { id: , name: 'Big cut rubber', rate: 95 },
            { id: , name: 'BIG RING 8T', rate: 2450 },
            { id: , name: 'Blower nabh 35mm+30mm', rate: 630 },
            { id: , name: 'Blower nabh kartar', rate: 850 },
            { id: , name: 'BLOWER SHAFT 35 MM', rate: 2090 },
            { id: , name: 'Blue pipe th. 8mm', rate: 14 },
            { id: , name: 'BREAK DRUM 2511', rate: 1800 },
            { id: , name: 'Break Kaliper assembly sumo TVS rate, rate: 1950 },
            { id: , name: 'Break Kaliper pin sumo', rate: 90 },
            { id: , name: 'Break pad red PTR', rate: 650 },
            { id: , name: 'Break pad tvs rate, rate: 700 },
            { id: , name: 'Break shoe 2011 small complete', rate: 390 },
            { id: , name: 'Break shoe 5911 big complete', rate: 450 },
            { id: , name: 'Breather cap', rate: 550 },
            { id: , name: 'Butterfly Nipple 10mm MS', rate: 150 },
            { id: , name: 'Butterfly Nipple 8.5mm brass', rate: 150 },
            { id: , name: 'CAME SHAFT 35 MM', rate: 0 },
            { id: , name: 'Came shaft 6no. 30mm', rate: 1550 },
            { id: , name: 'Castrol oil 900ml', rate: 280 },
            { id: , name: 'CATTER 2.5 SOOT', rate: 20 },
            { id: , name: 'Center pin bush dashmesh', rate: 510 },
            { id: , name: 'Center pin bush GDR', rate: 770 },
            { id: , name: 'Center pin bush kartar N/M', rate: 950 },
            { id: , name: 'Center pin bush PTL', rate: 590 },
            { id: , name: 'Center pin bush vishal', rate: 610 },
            { id: , name: 'CHAIN SPROCKET 14/35 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 15/30 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 15/35 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 18/35', rate: 270 },
            { id: , name: 'CHAIN SPROCKET 20/30 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 22/30 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 24/30 HC', rate: 0 },
            { id: , name: 'CHAIN SPROCKET 24/35', rate: 0 },
            { id: , name: 'CHANGER COMPLETE', rate: 12800 },
            { id: , name: 'Check valve 50c HTP', rate: 45 },
            { id: , name: 'Check valve 80c HTP', rate: 100 },
            { id: , name: 'Chidi 10mm+12mm', rate: 50 },
            { id: , name: 'CHISEL 10\, rate: 210 },
            { id: , name: 'CHISEL 6\, rate: 130 },
            { id: , name: 'Class blade shinetec', rate: 750 },
            { id: , name: 'Clutch bush 110mm  PTL', rate: 850 },
            { id: , name: 'Clutch chilam 1312', rate: 850 },
            { id: , name: 'Clutch fork GDR', rate: 650 },
            { id: , name: 'CLUTCH SHAFT PREET 5TH', rate: 6200 },
            { id: , name: 'Coolent bottle', rate: 650 },
            { id: , name: 'COUNTER SHAFT 4X4 PREET', rate: 6950 },
            { id: , name: 'COUNTER SHAFT 5TH KARTAR', rate: 6200 },
            { id: , name: 'COUNTER SHAFT 5TH PREET', rate: 6200 },
            { id: , name: 'COUNTER SHAFT PTL (K)', rate: 4100 },
            { id: , name: 'COUNTER SHAFT PTL (P)', rate: 4100 },
            { id: , name: 'Crank 5x6x51\, rate: 6200 },
            { id: , name: 'CRANK 5X7X51\, rate: 6800 },
            { id: , name: 'CRANK 6X6X51\, rate: 6800 },
            { id: , name: 'CRANK 6X7X51\, rate: 7000 },
            { id: , name: 'DAname, rate: 30 },
            { id: , name: 'DAB PATTI heavy', rate: 16 },
            { id: , name: 'Diesel filter 1 Liter', rate: 220 },
            { id: , name: 'DISK TAWA 12 T', rate: 1750 },
            { id: , name: 'DISK TAWA 14 T', rate: 1750 },
            { id: , name: 'DISK TAWA 16 T', rate: 1650 },
            { id: , name: 'DISK TAWA 20 T', rate: 1650 },
            { id: , name: 'DISK TAWA KARTAR', rate: 3050 },
            { id: , name: 'Distributer dowty', rate: 16900 },
            { id: , name: 'Drain pipe 42\' benrate, rate: 650 },
            { id: , name: 'Drain pipe 55\' benrate, rate: 670 },
            { id: , name: 'Drain pipe kartar', rate: 950 },
            { id: , name: 'Drain pipe turbo', rate: 850 },
            { id: , name: 'EDEL 6205 3/4\, rate: 230 },
            { id: , name: 'EDEL 6205 5/8\, rate: 190 },
            { id: , name: 'Electric lans adjustable yellow', rate: 50 },
            { id: , name: 'Electric pump delivery pipe', rate: 60 },
            { id: , name: 'Electric pump gun', rate: 260 },
            { id: , name: 'Elevator chain 40 pad class', rate: 4900 },
            { id: , name: 'Elevator chain 40 pad kdv', rate: 4880 },
            { id: , name: 'Elevator kundi nm', rate: 170 },
            { id: , name: 'F 206', rate: 350 },
            { id: , name: 'F 207', rate: 460 },
            { id: , name: 'F 209', rate: 520 },
            { id: , name: 'F 211', rate: 0 },
            { id: , name: 'F211', rate: 750 },
            { id: , name: 'Feeder chain 21x42 daimonrate, rate: 8800 },
            { id: , name: 'Feeder chain 21x42 kartar delux', rate: 10200 },
            { id: , name: 'Feeder chain 21x42 kdv', rate: 7500 },
            { id: , name: 'FEEDER FATTI 27\' LIGHT', rate: 150 },
            { id: , name: 'FEEDER FULL LOCK', rate: 60 },
            { id: , name: 'FEEDER FULL LOCK CLASS', rate: 60 },
            { id: , name: 'Feeder gear 10x35', rate: 680 },
            { id: , name: 'Feeder gear 20x35', rate: 1040 },
            { id: , name: 'Feeder gear 24x35', rate: 1350 },
            { id: , name: 'FEEDER HALF LOCK', rate: 60 },
            { id: , name: 'FEEDER JACK 31/40', rate: 3650 },
            { id: , name: 'FEEDER JACK 31/45', rate: 3750 },
            { id: , name: 'FEEDER JACK 34/40', rate: 3650 },
            { id: , name: 'FEEDER JACK 34/45', rate: 3750 },
            { id: , name: 'FEEDER KAN LOCK', rate: 80 },
            { id: , name: 'FINGER HALF CLASS GAGAN', rate: 180 },
            { id: , name: 'FINGER HALF CLASS SPOT', rate: 190 },
            { id: , name: 'FINGER HALF CLASS STrate, rate: 170 },
            { id: , name: 'Finger half class tempered gagan', rate: 230 },
            { id: , name: 'Finger half class vishal strate, rate: 170 },
            { id: , name: 'Finger red gagan', rate: 240 },
            { id: , name: 'Flat adel 6207', rate: 1680 },
            { id: , name: 'Flat adel 6207 (H) preet', rate: 2290 },
            { id: , name: 'Flat adel shaft n/m', rate: 690 },
            { id: , name: 'Flat edel 6207 steel', rate: 2050 },
            { id: , name: 'Flate adel shaft o/m', rate: 690 },
            { id: , name: 'FULL LOCK 5/8\, rate: 30 },
            { id: , name: 'GEAR 2ND & 3RD PTL Gname, rate: 5800 },
            { id: , name: 'Gear fork nut', rate: 25 },
            { id: , name: 'Gear goli kit', rate: 50 },
            { id: , name: 'Gear handi Preet Rocky', rate: 15500 },
            { id: , name: 'Gear knob all', rate: 80 },
            { id: , name: 'GEAR ROD GDR', rate: 390 },
            { id: , name: 'Grease gun pipe 12\, rate: 80 },
            { id: , name: 'Grease gun pipe 15\, rate: 90 },
            { id: , name: 'Grease gun pipe 18\, rate: 100 },
            { id: , name: 'Grease gun pipe 24\, rate: 120 },
            { id: , name: 'GUCCHA SHAFT 30 MM 68\, rate: 0 },
            { id: , name: 'GUCCHA SHAFT 35 MM 68\, rate: 0 },
            { id: , name: 'GUCHHA SHAFT 30 MM 46\, rate: 1690 },
            { id: , name: 'GUCHHA SHAFT 30 MM 72\, rate: 1800 },
            { id: , name: 'GUCHHA SHAFT 35 MM 46\, rate: 2050 },
            { id: , name: 'GUCHHA SHAFT 35 MM 72\, rate: 2100 },
            { id: , name: 'Guidrum pin', rate: 150 },
            { id: , name: 'Guidrum shaft 11no.', rate: 5700 },
            { id: , name: 'Gutka 5 wala T2', rate: 130 },
            { id: , name: 'HALF LOCK 5/8\, rate: 30 },
            { id: , name: 'Haval 6205 Double bearing N/M', rate: 820 },
            { id: , name: 'Haval 6205 singel bearing N/M', rate: 780 },
            { id: , name: 'Head 22\' N/M', rate: 190 },
            { id: , name: 'HEAD BUSH 6205 D/name, rate: 80 },
            { id: , name: 'Head dashmesh', rate: 480 },
            { id: , name: 'Head k.s', rate: 480 },
            { id: , name: 'HEAD PILLOW 6205 S/B DEGI', rate: 580 },
            { id: , name: 'Head pillow 6205 steel d/name, rate: 600 },
            { id: , name: 'Head pillow 6205 steel s/name, rate: 450 },
            { id: , name: 'Head preet', rate: 690 },
            { id: , name: 'HIGHLOW JACK 22 MM', rate: 2150 },
            { id: , name: 'HIGHLOW JACK 28 MM', rate: 2550 },
            { id: , name: 'Hose Nipple 10mm', rate: 60 },
            { id: , name: 'Hose pipe 1\, rate: 257 },
            { id: , name: 'HOUSE PIPE Z LONG', rate: 260 },
            { id: , name: 'HTP control valve 50c', rate: 260 },
            { id: , name: 'HTP control valve 80c', rate: 480 },
            { id: , name: 'HTP Roller Light', rate: 350 },
            { id: , name: 'HTP suction pipe', rate: 650 },
            { id: , name: 'Hub 39T rvs', rate: 4450 },
            { id: , name: 'HUB BOLT KARTAR SMALL', rate: 90 },
            { id: , name: 'HUB BOLT SMALL', rate: 60 },
            { id: , name: 'Hub R/W GDR', rate: 2050 },
            { id: , name: 'Hydraulic filter nut big', rate: 150 },
            { id: , name: 'Hydraulic pump adopter', rate: 3250 },
            { id: , name: 'Hydrolic filter O/T', rate: 650 },
            { id: , name: 'JACK ROD 3 FEET', rate: 650 },
            { id: , name: 'JACK ROD 5 FEET', rate: 890 },
            { id: , name: 'JAIN PAPER', rate: 170 },
            { id: , name: 'Jvk 32208 bearing', rate: 360 },
            { id: , name: 'KAPDA BLACK', rate: 500 },
            { id: , name: 'KAPDA FOJI', rate: 600 },
            { id: , name: 'KAPDA GREEN', rate: 550 },
            { id: , name: 'KARCHHI BHARAT 205 NO.', rate: 620 },
            { id: , name: 'KING PIN 1210 STrate, rate: 450 },
            { id: , name: 'KING PIN BUSH', rate: 180 },
            { id: , name: 'King pin kit gdr', rate: 130 },
            { id: , name: 'King pin kit kartar N/M', rate: 170 },
            { id: , name: 'L HOUSE PIPE', rate: 190 },
            { id: , name: 'L ROD 18\, rate: 450 },
            { id: , name: 'L rod 18\' heavy', rate: 450 },
            { id: , name: 'L/R socket 10mm brass', rate: 120 },
            { id: , name: 'L/R socket 8.5mm brass', rate: 90 },
            { id: , name: 'Level pipe 24\, rate: 85 },
            { id: , name: 'Level pipe 27\, rate: 90 },
            { id: , name: 'Level pipe 30\, rate: 100 },
            { id: , name: 'LOCK 160 MM', rate: 90 },
            { id: , name: 'LOCK 6207', rate: 20 },
            { id: , name: 'LOCK PLASS 10\' INNER', rate: 300 },
            { id: , name: 'LOCK PLASS 7\' INNER', rate: 170 },
            { id: , name: 'Lota 100no.', rate: 850 },
            { id: , name: 'Lota 50no.', rate: 500 },
            { id: , name: 'Low rate 6205 bearing', rate: 80 },
            { id: , name: 'M D PLATE 14\, rate: 2650 },
            { id: , name: 'M D PLATE 16\, rate: 2950 },
            { id: , name: 'M-type blade shinetec', rate: 750 },
            { id: , name: 'Macchi bush tyer', rate: 14 },
            { id: , name: 'MOTOR CAP KARTAR 5TH', rate: 190 },
            { id: , name: 'MOTOR PINION 17T', rate: 790 },
            { id: , name: 'MOTOR T KARTAR', rate: 750 },
            { id: , name: 'Nutnipple 10mm', rate: 80 },
            { id: , name: 'Oil filter bb382 bnname, rate: 260 },
            { id: , name: 'Oil pipe 14feet', rate: 460 },
            { id: , name: 'Oil pipe 21 feet', rate: 690 },
            { id: , name: 'Over flow pipe 96\, rate: 260 },
            { id: , name: 'PAD CLASS', rate: 15 },
            { id: , name: 'PAD GDR', rate: 15 },
            { id: , name: 'PAD PREET', rate: 15 },
            { id: , name: 'PAD PTL', rate: 20 },
            { id: , name: 'PAD SOYABIN', rate: 50 },
            { id: , name: 'Pinion kartar double seal rvs', rate: 2550 },
            { id: , name: 'Pinion kartar single seal rvs', rate: 2390 },
            { id: , name: 'PLAIN BUSH PREET', rate: 180 },
            { id: , name: 'Poiner finger half class', rate: 280 },
            { id: , name: 'Preet oil break pad 17T', rate: 590 },
            { id: , name: 'Pressure horn pipe 240\, rate: 240 },
            { id: , name: 'Pressure jack big', rate: 3550 },
            { id: , name: 'PULLER ROD 17\, rate: 120 },
            { id: , name: 'PULLER ROD PTL', rate: 120 },
            { id: , name: 'PULLY PIN BUSH', rate: 140 },
            { id: , name: 'Pump makhi', rate: 100 },
            { id: , name: 'PUMP PULLY 10\' A', rate: 720 },
            { id: , name: 'PUMP PULLY 10\' name, rate: 720 },
            { id: , name: 'PUMP PULLY 10.5\' name, rate: 760 },
            { id: , name: 'PUMP PULLY 8\' A', rate: 580 },
            { id: , name: 'PUMP PULLY 8\' name, rate: 580 },
            { id: , name: 'PUMP PULLY 9\' A', rate: 650 },
            { id: , name: 'PUMP PULLY 9.5\' name, rate: 690 },
            { id: , name: 'Push pull switch small', rate: 40 },
            { id: , name: 'Reaper blade Panther', rate: 550 },
            { id: , name: 'Reaper huname, rate: 1760 },
            { id: , name: 'REEL FIRKI 6205 N/T GDR', rate: 220 },
            { id: , name: 'REEL JACK', rate: 1980 },
            { id: , name: 'REEM BIG', rate: 9200 },
            { id: , name: 'Rim plate big', rate: 1150 },
            { id: , name: 'Rim plate small', rate: 850 },
            { id: , name: 'Rivet kg rate', rate: 200 },
            { id: , name: 'RIVET MIX GAGAN', rate: 200 },
            { id: , name: 'Rollon blade class 2mm', rate: 480 },
            { id: , name: 'Sa 205', rate: 360 },
            { id: , name: 'Sa 206', rate: 490 },
            { id: , name: 'Sa 207', rate: 615 },
            { id: , name: 'SEEP 47X49', rate: 4490 },
            { id: , name: 'SEEP 48X25', rate: 2540 },
            { id: , name: 'SEEP 48X26', rate: 2635 },
            { id: , name: 'SEEP 48X30', rate: 3010 },
            { id: , name: 'SEEP 48X55', rate: 5150 },
            { id: , name: 'SEEP 48X56', rate: 5245 },
            { id: , name: 'SEEP 48X57', rate: 5335 },
            { id: , name: 'SEEP 48X58', rate: 5430 },
            { id: , name: 'SEEP 48X60', rate: 5620 },
            { id: , name: 'SEEP 48X62', rate: 5810 },
            { id: , name: 'Seep tar', rate: 50 },
            { id: , name: 'Self kada', rate: 2200 },
            { id: , name: 'Servo 1 Liter', rate: 250 },
            { id: , name: 'Shell clamp goli gdr', rate: 120 },
            { id: , name: 'Shell goli gdr', rate: 120 },
            { id: , name: 'Shell goli ptl', rate: 120 },
            { id: , name: 'SILENCER JAIN', rate: 50 },
            { id: , name: 'Sleeve 16T coupling rvs', rate: 390 },
            { id: , name: 'Sleeve 20T coupling rvs', rate: 390 },
            { id: , name: 'SMALL COUPLER 25T', rate: 1490 },
            { id: , name: 'Sonalika aircleaner assm. Steel cap', rate: 380 },
            { id: , name: 'Speedometer cable 156\' 13feet', rate: 430 },
            { id: , name: 'Speedometer cable 180\' 15feet', rate: 490 },
            { id: , name: 'Speedometer cable 42\'3.5feet', rate: 210 },
            { id: , name: 'Spendel bush PTL', rate: 490 },
            { id: , name: 'SPIKE MALKIT', rate: 0 },
            { id: , name: 'SPIKE N/M', rate: 0 },
            { id: , name: 'SPIKE VISHAL', rate: 0 },
            { id: , name: 'Spring kit gb50', rate: 490 },
            { id: , name: 'Star 18x18 supros', rate: 1480 },
            { id: , name: 'Star 21x21 supros', rate: 1590 },
            { id: , name: 'Starforce blade class 2mm', rate: 750 },
            { id: , name: 'Std blade class 2mm', rate: 450 },
            { id: , name: 'STEARING JACK 22 MM', rate: 2650 },
            { id: , name: 'STEARING JACK 28 MM', rate: 2850 },
            { id: , name: 'Stearing pipe 14mm 22\, rate: 330 },
            { id: , name: 'Stearing pipe arjun', rate: 490 },
            { id: , name: 'Stearing pipe farmtrac', rate: 410 },
            { id: , name: 'Stearing pipe Jhondheer', rate: 590 },
            { id: , name: 'Stearing pipe sonalika', rate: 410 },
            { id: , name: 'Steering jack 22mm', rate: 2450 },
            { id: , name: 'Steering pipe 14mm 30\, rate: 450 },
            { id: , name: 'Strip 15feet 3/4\, rate: 900 },
            { id: , name: 'Strip 15feet 6mm', rate: 900 },
            { id: , name: 'Strip 8.5feet force', rate: 600 },
            { id: , name: 'Tata cross panther', rate: 550 },
            { id: , name: 'TEMP METER 21 FEET', rate: 890 },
            { id: , name: 'TEMP METER ELECTRONIC', rate: 0 },
            { id: , name: 'Temperature meter 5feet wire kkk', rate: 510 },
            { id: , name: 'Temperature meter swaraj electric', rate: 850 },
            { id: , name: 'Thresher shaft 11no.', rate: 5600 },
            { id: , name: 'TINE 11\' HEAVY', rate: 45 },
            { id: , name: 'TINE 11\' LIGHT', rate: 38 },
            { id: , name: 'TINE 9\' HEAVY', rate: 42 },
            { id: , name: 'TINE 9\' LIGHT', rate: 35 },
            { id: , name: 'TRALLA HUK BOLT 16 MM', rate: 140 },
            { id: , name: 'TRALLA HUK BOLT 18 MM', rate: 160 },
            { id: , name: 'UC 205 MHR', rate: 250 },
            { id: , name: 'Uc 206', rate: 330 },
            { id: , name: 'Uc 207', rate: 420 },
            { id: , name: 'Uc 209', rate: 620 },
            { id: , name: 'Uc 210', rate: 740 },
            { id: , name: 'Uc 211', rate: 910 },
            { id: , name: 'Uc 212', rate: 1240 },
            { id: , name: 'Uc204 Light', rate: 170 },
            { id: , name: 'Uc208', rate: 530 },
            { id: , name: 'Ucf 205', rate: 420 },
            { id: , name: 'Ucf 206', rate: 570 },
            { id: , name: 'Ucf 208', rate: 885 },
            { id: , name: 'Ucf 209', rate: 980 },
            { id: , name: 'Ucf 210', rate: 1140 },
            { id: , name: 'Ucf 212', rate: 2120 },
            { id: , name: 'VARM 3 NO.', rate: 140 },
            { id: , name: 'VARM 4 NO.', rate: 140 },
            { id: , name: 'Viswkarma blade M-Type 2mm', rate: 450 },
            { id: , name: 'Water body combine 3416', rate: 2750 },
            { id: , name: 'Water body hino special', rate: 2690 },
            { id: , name: 'Water pump fan 20\' 8hole', rate: 1250 },
            { id: , name: 'White pipe th. 8mm', rate: 14 },
            { id: , name: 'WOODEN GUTKA 5', rate: 120 },
            { id: , name: 'WOODEN GUTKA 6', rate: 120 },
            { id: , name: 'Yellow pipe 10mm', rate: 20 },
            { id: , name: 'Yellow pipe 8mm', rate: 16 },
            { id: , name: 'Z 22/23 T PREET', rate: 1950 },
            { id: , name: 'Z 23 5TH KARTAR', rate: 2400 },
            { id: , name: 'Z 27/17 5TH KARTAR', rate: 3210 },
            { id: , name: 'Z 31/41 3RD GEAR DASHMESH', rate: 4410 },
            { id: , name: 'Z 32 DASHMESH SPL', rate: 1730 },
            { id: , name: 'Z 32 PTL', rate: 1550 },
            { id: , name: 'Z 47 8T COUNTER GEAR PREET', rate: 5490 },
            { id: , name: 'Z HOUSE PIPE', rate: 190 },
            { id: , name: 'Z-79 sainik bullgear', rate: 10300 },
            { id: , name: 'Z73 crown 18hole sainik', rate: 6380 },
            { id: , name: 'Z73 crown kartar 13\' 19no. Rvs', rate: 4980 }
          // Add more products as needed
        ];

        let bill;

        function getRandomQuantity(temp) {          if(temp>1000)
            {            const randomNumber = Math.random();
             return randomNumber >= 0.5 ? 2 : 1;
            }
            else if(temp<=1000 && temp>=500)
            {               // Generate a random quantity between 1 and 10
            return Math.floor(Math.random() * 10) + 1;
            }
            else
            {               // Generate a random quantity between 1 and 10
            return Math.floor(Math.random() * 20) + 1;
            }
           
        }

        function getRandomProduct() 
        { 
            const productSize = 6;
            return Math.floor(Math.random() * productSize) + 1;
        }

        function getProductById(id) 
        {          return products.find(product => product.id === id);
        }

        function generateBill() {          const amount = parseFloat(document.getElementById('amount').value);
            if (isNaN(amount)) {              alert('Please enter a valid amount.');
                return;
            }

            const table = document.getElementById('bill-table');
            table.innerHTML = '<tr><th>#</th><th>Product Name</th><th>Rate</th><th>Quantity</th><th>Total</th></tr>';
            let amountLeft = amount;
            let total = 0;
            let i=1;
           while(amountLeft>0) {              if(amountLeft<50)
                {                  const row = table.insertRow(-1);
                    row.innerHTML = `
                    <td>${i}</td>
                    <td>${'Packaging'}</td>
                    <td>${amountLeft}</td>
                    <td>${1}</td>
                    <td>${amountLeft}</td>
                `;
                    break;
                }
                let product = getProductById(getRandomProduct());
                const quantity = getRandomQuantity(product.rate);
                const productTotal = quantity * product.rate;
                
                if(productTotal<amountLeft)
                {                  amountLeft -= productTotal;
                    const row = table.insertRow(-1);
                    row.innerHTML = `
                    <td>${i}</td>
                    <td>${product.name}</td>
                    <td>${product.rate}</td>
                    <td>${quantity}</td>
                    <td>${productTotal}</td>
                `;
                i++;
                }
                

            }
            
            

            const totalRow = table.insertRow(-1);
            totalRow.innerHTML = `<td colspan='4'><em><strong>Total</strong></em></td><td>${amount}</td>`;

        }

        function deleteProduct(button) {          const row = button.parentNode.parentNode;
            const productTotal = parseFloat(row.cells[3].innerText);
            const totalElement = document.getElementById('total');
            const total = parseFloat(totalElement.innerText.replace('Total: ', ''));
            totalElement.innerText = `Total: ${(total - productTotal).toFixed(2)}`;
            row.remove();
        }

        function showProducts() {          const table = document.getElementById('product-table');
            table.innerHTML = '<tr><th>#</th><th>Product Name</th><th>Rate</th></tr>';
            let i=1;
            for (const product of products) {              const row = table.insertRow(-1);
                row.innerHTML = `
                    <td>${i}</td>
                    <td>${product.name}</td>
                    <td>${product.rate}</td>
                `;
                i++;
            }
        }
